// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBs3IYujyuo_-iXfTVRRSVh4cgYfabGR8',
    appId: '1:1026032157199:web:b25071100ebba13abe197a',
    messagingSenderId: '1026032157199',
    projectId: 'evently-app-a7872',
    authDomain: 'evently-app-a7872.firebaseapp.com',
    storageBucket: 'evently-app-a7872.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJuVUF4anLjyGKXR17RbatbcFCWFacPqs',
    appId: '1:1026032157199:android:6ff5173ebc84b454be197a',
    messagingSenderId: '1026032157199',
    projectId: 'evently-app-a7872',
    storageBucket: 'evently-app-a7872.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiX1hdMG3NEmWG-F9cYisBe6v5HuqWJoQ',
    appId: '1:1026032157199:ios:6ff11136f7aaaa9ebe197a',
    messagingSenderId: '1026032157199',
    projectId: 'evently-app-a7872',
    storageBucket: 'evently-app-a7872.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );
}
